version: "3.8"

services:
  jellyfinbutton:
    build: .
    container_name: jellyfinbutton
    ports:
      - "${PORT}:${PORT}"
    restart: "no"
    environment:
      WEBHOOK_URL: ${WEBHOOK_URL}
      HA_URL: ${HA_URL}
      TOKEN: ${TOKEN}
      ENTITY_ID: ${ENTITY_ID}
      PORT: ${PORT}
    dns:
      - 1.1.1.1
      - 1.0.0.1