version: "3.8"

services:
  jellyfinbutton:
    build: .
    container_name: jellyfinbutton
    networks:
      - shared_network
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    environment:
      WEBHOOK_URL: ${WEBHOOK_URL}
      HA_URL: ${HA_URL}
      TOKEN: ${TOKEN}
      ENTITY_ID: ${ENTITY_ID}
      PORT: ${PORT}
      JELLYFIN_URL: ${JELLYFIN_URL}
      WEBHOOK_JELLYFINOff: ${WEBHOOK_JELLYFINOff}
      API_KEY: ${API_KEY}
      QBITUSER: ${QBITUSER}
      QBITPASS: ${QBITPASS}
      QBITIP: ${QBITIP}

    dns:
      - 1.1.1.1
      - 1.0.0.1

networks:
  shared_network:
    external: true